In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import spacy
from spacy import displacy
import networkx as nx
import os
import matplotlib.pyplot as plt
import scipy
import re
import country_converter as coco

In [2]:
# Load spacy English module

NER = spacy.load("en_core_web_sm")

In [3]:
# Load 20C text file
with open("20C_events_article_Wiki.txt", 'r', errors='ignore') as file:
    lines = file.readlines()

In [4]:
# Cutting out references and further reading sections
try:
    cut_index = lines.index("See also[edit]\n")  # everything from this on
    trimmed_data = ''.join(lines[:cut_index])
except ValueError:
    trimmed_data = ''.join(lines)

In [5]:
print(trimmed_data[-500:])

e possibility of human extinction, although not overnight but over several decades.[273] This prompted many nations to negotiate and sign the Kyoto treaty, which set mandatory limits on carbon dioxide emissions.[274]
The celebration of the 20th centuryâ€™s ending expressed the popular opinion that New Year's Eve 1999 and New Year's Day 2000 marked the turn of the millennium, while strictly speaking the 20th century ended on New Year's Eve 2000 and the 21st century began on New Year's Day 2001.

this worked, this is where the main article ends

Some of the main countries are referred to as different names in the text than the CSV, and especially the main countries. Russia:Soviet Union/USSR, United States: America/US, United Kingdom: Britain/Great Britain.
I've looked through all cases of 'America' and none refer to latin or central america.

In [6]:
# Loading countries csv
countries = pd.read_csv('countries.csv', index_col=False)
official_countries = countries['Country'].dropna().unique().tolist()

In [7]:
# getting country demonyms based off data from https://gist.github.com/consti/e2c7ddc64f0aa044a8b4fcd28dba0700 
df_demons = pd.read_csv('emoji_country_nationality_list.csv', usecols=['Name', 'Demonym 1', 'Demonym 2', 'Demonym 3'])
df_demons = df_demons.fillna('')
df_demons.head()

                   Name  Demonym 1 Demonym 2 Demonym 3
0               Andorra   Andorran
1  United Arab Emirates    Emirian   Emirati
2           Afghanistan    Afghani    Afghan
3   Antigua and Barbuda   Antiguan
4              Anguilla  Anguillan

In [8]:
# Demonym to country mapping
demonym_dict = {}   # empty list for dict

# loop through rows of demonym df, get country name from name column and convert to lower
for _, row in df_demons.iterrows(): 
    country = row['Name'].lower()
    for col in ['Demonym 1', 'Demonym 2', 'Demonym 3']:     # do it over all columns
        dem = row[col].strip().lower()
        if dem:
            demonym_dict[dem] = country

In [9]:
# integrate with country converter for other aliases 
cc = coco.CountryConverter()

# get the iso3 code, then convert it to official country name in lower case
def get_official(country_name):
    iso3 = cc.convert(names=country_name, to='ISO3')
    if isinstance(iso3, list):
        iso3 = iso3[0] if iso3 else None
    if not iso3 or iso3 == 'not found':
        return None
    name_short = cc.convert(names=iso3, to='name_short')
    if isinstance(name_short, list):
        name_short = name_short[0] if name_short else None
    return name_short.lower() if isinstance(name_short, str) else None

In [10]:
# Convert base demonym mapping to official standard names:
expanded_aliases = {}

# loop through key-value pairs in demonym dictionary
for dem, country in demonym_dict.items():
    std = get_official(country)     # get standard official name
    if std:
        expanded_aliases[dem] = std     # save to expanded aliases dict

congo (republic of) not found in regex

In [11]:
# Add official country names and their lowercase forms
for name in official_countries:
    std_name = get_official(name)
    if std_name:
        expanded_aliases[std_name] = std_name       # key=standard name itself
        expanded_aliases[name.lower()] = std_name

Abkhazia not found in regex
Artsakh not found in regex
Akrotiri not found in regex
Ascension Island not found in regex
Ashmore and Cartier Islands not found in regex
Bajo Nuveo Bank not found in regex
Baker Island not found in regex
Canary Islands not found in regex
Ceuta not found in regex
Chatham Islands not found in regex
Clipperton Island not found in regex
Coral Sea Islands not found in regex
Corsica not found in regex
Crimea not found in regex
Dagestan not found in regex
Dhekelia not found in regex
Donetsk not found in regex
Ducie Island not found in regex
Easter Island not found in regex
Galápagos Islands not found in regex
Gilgit-Baltistan not found in regex
Gagauzia not found in regex
Guantanamo Bank not found in regex
Henderson Island not found in regex
Herm not found in regex
Howland Island not found in regex
Jan Mayen not found in regex
Jarvis Island not found in regex
Jeju Island not found in regex
Jervis Bay not found in regex
Jethou not found in regex
Johnston Atoll not found in regex
Juan Fernández Islands not found in regex
Kaliningrad not found in regex
Kharkiv not found in regex
Kherson not found in regex
Kurdistan not found in regex
Lihou not found in regex
Luhansk not found in regex
Madeira not found in regex
Marion Island not found in regex
Melilla not found in regex
Midway Atoll not found in regex
Mykolaiv not found in regex
Adygea not found in regex
Northern Ireland not found in regex
Northwest Territories not found in regex
Nunavut not found in regex
Oecusse not found in regex
Oeno Island not found in regex
Palmyra Atoll not found in regex
Peñón de Vélez de la Gomera not found in regex
Prince Edward Island not found in regex
Puntland not found in regex
Ross Dependency not found in regex
Saba not found in regex
San Andrés and Providencia not found in regex
Sark not found in regex
Scotland not found in regex
Scott Island not found in regex
Serranilla Bank not found in regex
Sevastopol not found in regex
Sint Eustatius not found in regex
South Ossetia not found in regex
South Orkney Islands not found in regex
South Shetland Islands not found in regex
Swains Island not found in regex
Transnistria not found in regex
Tristan da Cunha not found in regex
Wake Island not found in regex
Wales not found in regex
Yukon not found in regex
Zaporizhzhia not found in regex
Agaléga not found in regex
Amsterdam Island not found in regex
Aves Island not found in regex
Alderney not found in regex
Alto Velo Island not found in regex
Banc du Geyser not found in regex
Bear Island not found in regex
Brecqhou not found in regex
Cargados Carajos Shoals not found in regex
Carriacou not found in regex
Crozet Islands not found in regex
Culebra not found in regex
Desecheo not found in regex
Glorioso Islands not found in regex
Heligoland not found in regex
Mona not found in regex
Monito not found in regex
Rodrigues Island not found in regex
Rotuma not found in regex
Tromelin Island not found in regex
Vieques not found in regex
Aksai Chin not found in regex
Azad Jammu and Kashmir not found in regex
John F. Kennedy Memorial not found in regex
South Tibet not found in regex
Adélie Land not found in regex
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
More than one regular expression match for Argentine Antarctica
Balleny Islands not found in regex
British Antarctic Territory not found in regex
Marie Byrd Land not found in regex
Adjara not found in regex
Altai not found in regex
Bangsamoro not found in regex
Bashkortostan not found in regex

In [12]:
print(expanded_aliases)

{'andorran': 'andorra', 'emirian': 'united arab emirates', 'emirati': 'united arab emirates', 'afghani': 'afghanistan', 'afghan': 'afghanistan', 'antiguan': 'antigua and barbuda', 'anguillan': 'anguilla', 'albanian': 'albania', 'alabanian': 'albania', 'armenian': 'armenia', 'hayastani': 'armenia', 'angolan': 'angola', 'antarctic': 'antarctica', 'argentine': 'argentina', 'argentinian': 'argentina', 'argentinean': 'argentina', 'samoan': 'samoa', 'austrian': 'austria', 'australian': 'australia', 'arubian': 'aruba', 'ålandic': 'aland islands', 'ålandish': 'aland islands', 'azerbaijani': 'azerbaijan', 'bosnian': 'bosnia and herzegovina', 'herzegovinian': 'bosnia and herzegovina', 'barbadian': 'barbados', 'barbadan': 'barbados', 'bajan': 'barbados', 'bangladeshi': 'bangladesh', 'belgian': 'belgium', 'burkinabe': 'burkina faso', 'bulgarian': 'bulgaria', 'bahrainian': 'bahrain', 'burundian': 'burundi', 'beninese': 'benin', 'barthélemois': 'st. barths', 'bermudan': 'bermuda', 'bruneian': 'brunei darussalam', 'bolivian': 'bolivia', 'brazilian': 'brazil', 'bahameese': 'bahamas', 'bahamian': 'bahamas', 'bhutanese': 'bhutan', 'motswana': 'botswana', 'batswana': 'botswana', 'belarusian': 'belarus', 'belizean': 'belize', 'canadian': 'canada', 'cocossian': 'cocos (keeling) islands', 'cocos islandia': 'cocos (keeling) islands', 'central african': 'central african republic', 'swiss': 'switzerland', 'ivorian': "cote d'ivoire", 'cook islander': 'cook islands', 'chilean': 'chile', 'cameroonian': 'cameroon', 'chinese': 'china', 'colombian': 'colombia', 'columbian': 'colombia', 'costa rican': 'costa rica', 'cuban': 'cuba', 'cape verdean': 'cabo verde', 'curaçaoan': 'curacao', 'christmas islander': 'christmas island', 'cypriot': 'cyprus', 'czech': 'czechia', 'german': 'germany', 'djiboutian': 'djibouti', 'djibouti': 'djibouti', 'danish': 'denmark', 'dane': 'denmark', 'dominican': 'dominican republic', 'algerian': 'algeria', 'ecuadorean': 'ecuador', 'ecudorean': 'ecuador', 'estonian': 'estonia', 'egyptian': 'egypt', 'western saharan': 'western sahara', 'sahrawi': 'western sahara', 'eritrean': 'eritrea', 'spanish': 'spain', 'ethiopian': 'ethiopia', 'finnish': 'finland', 'fijian': 'fiji', 'falkland islander': 'falkland islands', 'micronesian': 'micronesia, fed. sts.', 'faroese': 'faroe islands', 'french': 'france', 'gabonese': 'gabon', 'british': 'united kingdom', 'grenadian': 'grenada', 'georgian': 'georgia', 'french guianese': 'french guiana', 'ghanaian': 'ghana', 'ghanian': 'ghana', 'gibraltarian': 'gibraltar', 'greenlander': 'greenland', 'greenlandic': 'greenland', 'gambian': 'gambia', 'guinean': 'guinea-bissau', 'guadeloupean': 'guadeloupe', 'equatorial guinean': 'equatorial guinea', 'equatoguinean': 'equatorial guinea', 'greek': 'greece', 'guatemalan': 'guatemala', 'guamanian': 'guam', 'guyanese': 'guyana', 'hong konger': 'hong kong', 'honduran': 'honduras', 'croatian': 'croatia', 'croat': 'croatia', 'haitian': 'haiti', 'hungarian': 'hungary', 'indonesian': 'indonesia', 'irish': 'ireland', 'israeli': 'israel', 'manx': 'isle of man', 'indian': 'india', 'iraqi': 'iraq', 'iranian': 'iran', 'icelander': 'iceland', 'italian': 'italy', 'jamaican': 'jamaica', 'jordanian': 'jordan', 'japanese': 'japan', 'kenyan': 'kenya', 'kyrgyzstani': 'kyrgyz republic', 'cambodian': 'cambodia', 'i-kiribati': 'kiribati', 'comoran': 'comoros', 'kittian': 'st. kitts and nevis', 'nevisian': 'st. kitts and nevis', 'north korean': 'north korea', 'south korean': 'south korea', 'kuwaiti': 'kuwait', 'caymanian': 'cayman islands', 'kazakhstani': 'kazakhstan', 'kazakh': 'kazakhstan', 'laotian': 'laos', 'lebanese': 'lebanon', 'saint lucian': 'st. lucia', 'liechtensteiner': 'liechtenstein', 'sri lankan': 'sri lanka', 'liberian': 'liberia', 'mosotho': 'lesotho', 'basotho': 'lesotho', 'lithunian': 'lithuania', 'luxembourger': 'luxembourg', 'latvian': 'latvia', 'libyan': 'libya', 'moroccan': 'morocco', 'monacan': 'monaco', 'moldovan': 'moldova', 'montenegrin': 'montenegro', 'malagasy': 'madagascar', 'marshallese': 'marshall islands', 'macedonian': 'north macedonia', 'malian': 'mali', 'myanmarese': 'myanmar', 'burmese': 'myanmar', 'mongolian': 'mongolia', 'macanese': 'macau', 'northern mariana islander': 'northern mariana islands', 'martinican': 'martinique', 'martiniquaís': 'martinique', 'mauritanian': 'mauritania', 'montserratian': 'montserrat', 'maltese': 'malta', 'mauritian': 'mauritius', 'maldivan': 'maldives', 'malawian': 'malawi', 'mexican': 'mexico', 'malaysian': 'malaysia', 'mozambican': 'mozambique', 'namibian': 'namibia', 'new caledonian': 'new caledonia', 'new caledonians': 'new caledonia', 'nigerien': 'niger', 'norfolk islander': 'norfolk island', 'nigerian': 'nigeria', 'nicaraguan': 'nicaragua', 'nicoya': 'nicaragua', 'dutch': 'netherlands', 'norwegian': 'norway', 'nepalese': 'nepal', 'nauruan': 'nauru', 'niuean': 'niue', 'new zealander': 'new zealand', 'omani': 'oman', 'panamanian': 'panama', 'peruvian': 'peru', 'french polynesian': 'french polynesia', 'papua new guinean': 'papua new guinea', 'filipino': 'philippines', 'pakistani': 'pakistan', 'polish': 'poland', 'pole': 'poland', 'saint-pierrais': 'st. pierre and miquelon', 'miquelonnais': 'st. pierre and miquelon', 'pitcairn islander': 'pitcairn', 'puerto rican': 'puerto rico', 'palestinian': 'palestine', 'portuguese': 'portugal', 'portugese': 'portugal', 'palauan': 'palau', 'paraguayan': 'paraguay', 'qatari': 'qatar', 'romanian': 'romania', 'serbian': 'serbia', 'serb': 'serbia', 'russian': 'russia', 'rwandan': 'rwanda', 'rwandese': 'rwanda', 'saudi arabian': 'saudi arabia', 'saudi': 'saudi arabia', 'solomon islander': 'solomon islands', 'seychellois': 'seychelles', 'sudanese': 'south sudan', 'swedish': 'sweden', 'swede': 'sweden', 'singaporean': 'singapore', 'saint helenian': 'st. helena', 'slovenian': 'slovenia', 'slovene': 'slovenia', 'slovakian': 'slovakia', 'slovak': 'slovakia', 'sierra leonean': 'sierra leone', 'sanmarinese': 'san marino', 'sammarinese': 'san marino', 'senegalese': 'senegal', 'somali': 'somalia', 'surinamer': 'suriname', 'surinamese': 'suriname', 'são tomean': 'sao tome and principe', 'sao tomean': 'sao tome and principe', 'salvadorean': 'el salvador', 'salvadoran': 'el salvador', 'syrian': 'syria', 'swazi': 'eswatini', 'turks and caicos islander': 'turks and caicos islands', 'chadian': 'chad', 'togolese': 'togo', 'thai': 'thailand', 'tajikistani': 'tajikistan', 'tokelauan': 'tokelau', 'timorese': 'timor-leste', 'turkmen': 'turkmenistan', 'tunisian': 'tunisia', 'tongan': 'tonga', 'turkish': 'türkiye', 'turk': 'türkiye', 'trinidadian': 'trinidad and tobago', 'tobagonian': 'trinidad and tobago', 'tuvaluan': 'tuvalu', 'taiwanese': 'taiwan', 'tanzanian': 'tanzania', 'ukrainian': 'ukraine', 'ugandan': 'uganda', 'american': 'united states', 'uruguayan': 'uruguay', 'uzbekistani': 'uzbekistan', 'saint vincentian': 'st. vincent and the grenadines', 'vincentian': 'st. vincent and the grenadines', 'venezuelan': 'venezuela', 'virgin islander': 'united states virgin islands', 'vietnamese': 'vietnam', 'ni-vanuatu': 'vanuatu', 'wallisian': 'wallis and futuna islands', 'futunan': 'wallis and futuna islands', 'yemeni': 'yemen', 'yemenese': 'yemen', 'mahoran': 'mayotte', 'south african': 'south africa', 'zambian': 'zambia', 'zimbabwean': 'zimbabwe', 'afghanistan': 'afghanistan', 'albania': 'albania', 'algeria': 'algeria', 'andorra': 'andorra', 'angola': 'angola', 'antigua and barbuda': 'antigua and barbuda', 'argentina': 'argentina', 'armenia': 'armenia', 'australia': 'australia', 'austria': 'austria', 'azerbaijan': 'azerbaijan', 'bahamas': 'bahamas', 'bahrain': 'bahrain', 'bangladesh': 'bangladesh', 'barbados': 'barbados', 'belarus': 'belarus', 'belgium': 'belgium', 'belize': 'belize', 'benin': 'benin', 'bhutan': 'bhutan', 'bolivia': 'bolivia', 'bosnia and herzegovina': 'bosnia and herzegovina', 'botswana': 'botswana', 'brazil': 'brazil', 'brunei darussalam': 'brunei darussalam', 'brunei': 'brunei darussalam', 'bulgaria': 'bulgaria', 'burkina faso': 'burkina faso', 'burundi': 'burundi', 'cabo verde': 'cabo verde', 'cambodia': 'cambodia', 'cameroon': 'cameroon', 'canada': 'canada', 'central african republic': 'central african republic', 'chad': 'chad', 'chile': 'chile', 'china': 'china', 'colombia': 'colombia', 'comoros': 'comoros', 'costa rica': 'costa rica', "cote d'ivoire": "cote d'ivoire", "côte d'ivoire": "cote d'ivoire", 'croatia': 'croatia', 'cuba': 'cuba', 'cyprus': 'cyprus', 'czechia': 'czechia', 'dr congo': 'dr congo', 'democratic republic of the congo': 'dr congo', 'denmark': 'denmark', 'dominica': 'dominica', 'dominican republic': 'dominican republic', 'ecuador': 'ecuador', 'egypt': 'egypt', 'el salvador': 'el salvador', 'equatorial guinea': 'equatorial guinea', 'eritrea': 'eritrea', 'estonia': 'estonia', 'eswatini': 'eswatini', 'ethiopia': 'ethiopia', 'fiji': 'fiji', 'finland': 'finland', 'france': 'france', 'gabon': 'gabon', 'gambia': 'gambia', 'georgia': 'georgia', 'germany': 'germany', 'ghana': 'ghana', 'greece': 'greece', 'grenada': 'grenada', 'guatemala': 'guatemala', 'guinea': 'guinea', 'guinea-bissau': 'guinea-bissau', 'guyana': 'guyana', 'haiti': 'haiti', 'honduras': 'honduras', 'hungary': 'hungary', 'iceland': 'iceland', 'india': 'india', 'indonesia': 'indonesia', 'iran': 'iran', 'iraq': 'iraq', 'ireland': 'ireland', 'israel': 'israel', 'italy': 'italy', 'jordan': 'jordan', 'japan': 'japan', 'jamaica': 'jamaica', 'kazakhstan': 'kazakhstan', 'kenya': 'kenya', 'kiribati': 'kiribati', 'kuwait': 'kuwait', 'kyrgyz republic': 'kyrgyz republic', 'kyrgyzstan': 'kyrgyz republic', 'laos': 'laos', 'latvia': 'latvia', 'lebanon': 'lebanon', 'lesotho': 'lesotho', 'liberia': 'liberia', 'libya': 'libya', 'liechtenstein': 'liechtenstein', 'lithuania': 'lithuania', 'luxembourg': 'luxembourg', 'madagascar': 'madagascar', 'malawi': 'malawi', 'malaysia': 'malaysia', 'maldives': 'maldives', 'mali': 'mali', 'malta': 'malta', 'marshall islands': 'marshall islands', 'mauritania': 'mauritania', 'mauritius': 'mauritius', 'mexico': 'mexico', 'micronesia, fed. sts.': 'micronesia, fed. sts.', 'micronesia': 'micronesia, fed. sts.', 'moldova': 'moldova', 'monaco': 'monaco', 'mongolia': 'mongolia', 'montenegro': 'montenegro', 'morocco': 'morocco', 'mozambique': 'mozambique', 'myanmar': 'myanmar', 'namibia': 'namibia', 'nauru': 'nauru', 'nepal': 'nepal', 'netherlands': 'netherlands', 'new zealand': 'new zealand', 'nicaragua': 'nicaragua', 'niger': 'niger', 'nigeria': 'nigeria', 'north macedonia': 'north macedonia', 'north korea': 'north korea', 'norway': 'norway', 'oman': 'oman', 'pakistan': 'pakistan', 'palau': 'palau', 'palestine': 'palestine', 'panama': 'panama', 'papua new guinea': 'papua new guinea', 'paraguay': 'paraguay', 'peru': 'peru', 'philippines': 'philippines', 'poland': 'poland', 'portugal': 'portugal', 'qatar': 'qatar', 'congo republic': 'congo republic', 'republic of the congo': 'congo republic', 'romania': 'romania', 'russia': 'russia', 'rwanda': 'rwanda', 'st. kitts and nevis': 'st. kitts and nevis', 'saint kitts and nevis': 'st. kitts and nevis', 'st. lucia': 'st. lucia', 'saint lucia': 'st. lucia', 'st. vincent and the grenadines': 'st. vincent and the grenadines', 'saint vincent and the grenadines': 'st. vincent and the grenadines', 'samoa': 'samoa', 'san marino': 'san marino', 'sao tome and principe': 'sao tome and principe', 'são tomé and príncipe': 'sao tome and principe', 'saudi arabia': 'saudi arabia', 'senegal': 'senegal', 'serbia': 'serbia', 'seychelles': 'seychelles', 'sierra leone': 'sierra leone', 'singapore': 'singapore', 'slovakia': 'slovakia', 'slovenia': 'slovenia', 'solomon islands': 'solomon islands', 'somalia': 'somalia', 'south africa': 'south africa', 'south korea': 'south korea', 'south sudan': 'south sudan', 'spain': 'spain', 'sri lanka': 'sri lanka', 'sudan': 'sudan', 'suriname': 'suriname', 'sweden': 'sweden', 'switzerland': 'switzerland', 'syria': 'syria', 'tajikistan': 'tajikistan', 'tanzania': 'tanzania', 'thailand': 'thailand', 'timor-leste': 'timor-leste', 'timor leste': 'timor-leste', 'togo': 'togo', 'tonga': 'tonga', 'trinidad and tobago': 'trinidad and tobago', 'tunisia': 'tunisia', 'türkiye': 'türkiye', 'turkmenistan': 'turkmenistan', 'tuvalu': 'tuvalu', 'uganda': 'uganda', 'ukraine': 'ukraine', 'united arab emirates': 'united arab emirates', 'united kingdom': 'united kingdom', 'united states': 'united states', 'uruguay': 'uruguay', 'uzbekistan': 'uzbekistan', 'vanuatu': 'vanuatu', 'vatican': 'vatican', 'vatican city': 'vatican', 'venezuela': 'venezuela', 'vietnam': 'vietnam', 'yemen': 'yemen', 'zambia': 'zambia', 'zimbabwe': 'zimbabwe', 'aland islands': 'aland islands', 'åland islands': 'aland islands', 'american samoa': 'american samoa', 'anguilla': 'anguilla', 'aruba': 'aruba', 'bermuda': 'bermuda', 'bouvet island': 'bouvet island', 'british indian ocean territory': 'british indian ocean territory', 'british virgin islands': 'british virgin islands', 'cayman islands': 'cayman islands', 'chilean antarctic territory': 'chile', 'christmas island': 'christmas island', 'cocos (keeling) islands': 'cocos (keeling) islands', 'cook islands': 'cook islands', 'curacao': 'curacao', 'curaçao': 'curacao', 'falkland islands': 'falkland islands', 'faroe islands': 'faroe islands', 'french guiana': 'french guiana', 'french polynesia': 'french polynesia', 'french southern territories': 'french southern territories', 'french southern and antarctic lands': 'french southern territories', 'greenland': 'greenland', 'gibraltar': 'gibraltar', 'guadeloupe': 'guadeloupe', 'guam': 'guam', 'guernsey': 'guernsey', 'heard and mcdonald islands': 'heard and mcdonald islands', 'heard island and mcdonald islands': 'heard and mcdonald islands', 'hong kong': 'hong kong', 'isle of man': 'isle of man', 'jersey': 'jersey', 'karakalpakstan': 'pakistan', 'kosovo': 'kosovo', 'macau': 'macau', 'martinique': 'martinique', 'mayotte': 'mayotte', 'montserrat': 'montserrat', 'new caledonia': 'new caledonia', 'niue': 'niue', 'norfolk island': 'norfolk island', 'northern cyprus': 'cyprus', 'northern mariana islands': 'northern mariana islands', 'order of malta': 'malta', 'pitcairn': 'pitcairn', 'pitcairn island': 'pitcairn', 'puerto rico': 'puerto rico', 'reunion': 'reunion', 'réunion': 'reunion', 'st. barths': 'st. barths', 'saint barthélemy': 'st. barths', 'st. helena': 'st. helena', 'saint helena': 'st. helena', 'saint-martin': 'saint-martin', 'saint martin': 'saint-martin', 'st. pierre and miquelon': 'st. pierre and miquelon', 'saint pierre and miquelon': 'st. pierre and miquelon', 'sint maarten': 'sint maarten', 'somaliland': 'somalia', 'south georgia and south sandwich is.': 'south georgia and south sandwich is.', 'south georgia': 'south georgia and south sandwich is.', 'south sandwich islands': 'south georgia and south sandwich is.', 'svalbard and jan mayen islands': 'svalbard and jan mayen islands', 'svalbard': 'svalbard and jan mayen islands', 'taiwan': 'taiwan', 'tokelau': 'tokelau', 'turks and caicos islands': 'turks and caicos islands', 'united states virgin islands': 'united states virgin islands', 'wallis and futuna islands': 'wallis and futuna islands', 'wallis and futuna': 'wallis and futuna islands', 'western sahara': 'western sahara', 'petite martinique': 'martinique', 'australian capital territory': 'australia', 'antarctica': 'antarctica', 'argentine antarctica': 'antarctica', 'australian antarctic territory': 'australia'}

In [13]:
# Adding manual aliases
manual_aliases = {
    'britain': 'united kingdom',
    'great britain': 'united kingdom',
    'british': 'united kingdom',
    'america': 'united states',
    'u.s.': 'united states',
    'u.s.a.': 'united states',
    'south korea': 'korea, republic of',
    'north korea': 'korea, democratic people\'s republic of',
    'ussr': 'russia',
    'soviet': 'russia'
}

# Update expanded_aliases with manual entries (lowercase keys)
for alias, std_name in manual_aliases.items():
    expanded_aliases[alias.lower()] = std_name.lower()

In [14]:
# Process book with spacy NER
doc = NER(trimmed_data)

Getting named entity list per sentence

In [15]:
df_sentences = [] # empty shell to store results

# Loop through sentences, get entity list for each sentence
for sent in doc.sents:
    entity_list = [ent.text for ent in sent.ents]
    df_sentences.append({"sentence": sent, "entities": entity_list})
    
df_sentences = pd.DataFrame(df_sentences)

In [16]:
df_sentences.head(10)

,sentence,entities
0,"(\n\n\n\n, Key, events, of, the, 20th, century...","[the 20th century - Wikipedia, Jump, Main, Mai..."
1,"(1.4.1, \n, The, war, in, Europe, \n\n\n\n\n\n...","[1.4.1, Europe, 1.4.2, Blitzkrieg, 1.4.3, Oper..."
2,"(The, World, Wars, sparked, tension, between, ...","[the Cold War, the Space Race, the World Wide ..."
3,"(These, advancements, have, played, a, signifi...","[the 21st century, today]"
4,"(Historic, events, in, the, 20th, century[edit...","[Historic, 20th, World, Main, the 20th century]"
5,"(The, 1900s, saw, the, decade, herald, a, seri...","[The 1900s, the decade]"
6,"(1914, saw, the, completion, of, the, Panama, ...",[the Panama Canal]
7,"(The, Scramble, for, Africa, continued, in, th...","[Scramble, Africa, the 1900s]"
8,"(The, atrocities, in, the, Congo, Free, State,...",[the Congo Free State]
9,"(From, 1914, to, 1918, ,, the, First, World, W...","[1914 to 1918, the First World War]"

Filtering entities from article

In [17]:
# Function to filter out entities not of interest

def filter_entity(ent_list, alias_dict):
    return [ent for ent in ent_list if ent.lower() in alias_dict]

In [18]:
# Apply this to sentences df
df_sentences["country_entities"] = df_sentences["entities"].apply(
    lambda ents: filter_entity(ents, expanded_aliases)
)

In [19]:
filter_entity(["American","Zambia", "CF", "2"], expanded_aliases)

['American', 'Zambia']

In [20]:
df_sentences['country_entities'].head(20)

0                     [Spanish]
1                    [Japanese]
2                            []
3                            []
4                            []
5                            []
6                            []
7                            []
8                            []
9                            []
10                           []
11                           []
12    [France, Austria, Russia]
13            [Germany, Russia]
14                    [Germany]
15                           []
16          [Germany, American]
17                    [British]
18                           []
19                           []
Name: country_entities, dtype: object

In [21]:
# Filter out sentences with no country entities
df_sentences_filtered = df_sentences[df_sentences['country_entities'].map(len) > 0]

In [22]:
df_sentences_filtered.tail(10)

,sentence,entities,country_entities
279,"(In, the, 1990s, ,, work, on, the, Internation...","[the 1990s, the International Space Station, t...","[Russia, Japan]"
283,"(The, Sino, -, Soviet, split, had, removed, th...","[Sino-Soviet, USSR, the People's Republic of C...","[USSR, U.S.]"
284,"(Mikhail, Gorbachev, ,, its, last, leader, ,, ...","[Mikhail Gorbachev, Berlin, Soviet, Gorbachev,...",[Soviet]
285,"(Boris, Yeltsin, ,, president, of, Russia, ,, ...","[Boris Yeltsin, Russia]",[Russia]
320,"(The, people, of, the, Indian, subcontinent, ,...","[Indian, a sixth, the end of the century, firs...",[Indian]
321,"(China, ,, an, ancient, nation, comprising, a,...","[China, a fifth, West, East]",[China]
326,"(The, influence, of, China, and, India, was, a...","[China, India, West]","[China, India]"
331,"(Meanwhile, in, South, Africa, ,, the, aparthe...","[South Africa, Nelson Mandela, first, four and...",[South Africa]
332,"(In, Rwanda, ,, an, estimated, one, million, p...","[Rwanda, an estimated one million, Tutsis, Hut...",[Rwanda]
336,"(Despots, such, as, Kim, Jong, -, il, of, Nort...","[Kim Jong-il, North Korea]",[North Korea]

In [23]:
# map country entities to standardised name and lower case
def map_to_canonical(entities, alias_dict):
    return [alias_dict[ent.lower()] for ent in entities if ent.lower() in alias_dict]

In [24]:
df_sentences_filtered = df_sentences_filtered.copy()
df_sentences_filtered["country_canonicals"] = df_sentences_filtered["country_entities"].apply(
    lambda ents: map_to_canonical(ents, expanded_aliases)
)
df_sentences_filtered.tail(10)

,sentence,entities,country_entities,country_canonicals
279,"(In, the, 1990s, ,, work, on, the, Internation...","[the 1990s, the International Space Station, t...","[Russia, Japan]","[russia, japan]"
283,"(The, Sino, -, Soviet, split, had, removed, th...","[Sino-Soviet, USSR, the People's Republic of C...","[USSR, U.S.]","[russia, united states]"
284,"(Mikhail, Gorbachev, ,, its, last, leader, ,, ...","[Mikhail Gorbachev, Berlin, Soviet, Gorbachev,...",[Soviet],[russia]
285,"(Boris, Yeltsin, ,, president, of, Russia, ,, ...","[Boris Yeltsin, Russia]",[Russia],[russia]
320,"(The, people, of, the, Indian, subcontinent, ,...","[Indian, a sixth, the end of the century, firs...",[Indian],[india]
321,"(China, ,, an, ancient, nation, comprising, a,...","[China, a fifth, West, East]",[China],[china]
326,"(The, influence, of, China, and, India, was, a...","[China, India, West]","[China, India]","[china, india]"
331,"(Meanwhile, in, South, Africa, ,, the, aparthe...","[South Africa, Nelson Mandela, first, four and...",[South Africa],[south africa]
332,"(In, Rwanda, ,, an, estimated, one, million, p...","[Rwanda, an estimated one million, Tutsis, Hut...",[Rwanda],[rwanda]
336,"(Despots, such, as, Kim, Jong, -, il, of, Nort...","[Kim Jong-il, North Korea]",[North Korea],"[korea, democratic people's republic of]"

Create Relationships

In [25]:
# Defining relationships 

relationships = [] # create an empty list

for i in range(df_sentences_filtered.index[-1]):
    end_i = min(i+5, df_sentences_filtered.index[-1])
    country_list = sum((df_sentences_filtered.loc[i: end_i].country_canonicals), [])
    
    # Remove duplicated characters that are next to each other
    country_unique = [country_list[i] for i in range(len(country_list)) 
                   if (i==0) or country_list[i] != country_list[i-1]]
    
    if len(country_unique) > 1:
        for idx, a in enumerate(country_unique[:-1]):
            b = country_unique[idx + 1]
            relationships.append({"source": a, "target": b})

In [30]:
relationship_df = pd.DataFrame(relationships)

In [31]:
relationship_df

            source                                  target
0            spain                                   japan
1           france                                 austria
2          austria                                  russia
3           france                                 austria
4          austria                                  russia
...            ...                                     ...
1322  south africa                                  rwanda
1323  south africa                                  rwanda
1324  south africa                                  rwanda
1325        rwanda  korea, democratic people's republic of
1326        rwanda  korea, democratic people's republic of

[1327 rows x 2 columns]

In [32]:
# Sort the cases with a- >b and b- >a
relationships_df = pd.DataFrame(np.sort(relationship_df.values, axis = 1), 
                                columns = relationship_df.columns)
relationships_df.head(5)

    source  target
0    japan   spain
1  austria  france
2  austria  russia
3  austria  france
4  austria  russia

In [33]:
# Summarise the interactions and view sorted
relationships_df["value"] = 1
relationships_df = (
    relationships_df.groupby(["source","target"], 
                                          as_index=False)
    .sum()
    .sort_values("value", ascending=False)
)

relationships_df.head(10)

      source          target  value
27     china           japan     68
95     japan   united states     58
65   germany  united kingdom     54
61   germany          russia     53
59   germany           japan     48
54    france  united kingdom     45
116   russia   united states     40
90     japan          russia     37
66   germany   united states     32
48    france         germany     31

In [34]:
relationships_df.to_csv('20C_countries_relationships.csv')